apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-repo-pv
spec:
  storageClassName: docker-registry
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/repository
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-repo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 
  storageClassName: docker-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      nodeSelector:
        type: worker
      containers:
      - name: docker-registry
        image: registry
        ports:
        - containerPort: 5000
          name: docker-registry
        volumeMounts:
        - mountPath: /var/lib/registry
          name: docker-repo
      volumes:
      - name: docker-repo
        persistentVolumeClaim:
          claimName: docker-repo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: docker-registry
    nodePort: 30500
  selector:
    app: docker-registry
---
