apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alog-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alog-ws-front
                port:
                  number: 80
          - path: /api/users/permit-all
            pathType: Prefix
            backend:
              service:
                name: alog-service-user
                port:
                  number: 8081
          - path: /auth/permit-all
            pathType: Prefix
            backend:
              service:
                name: alog-service-auth
                port:
                  number: 8087